some cleanup

diff --git a/bashbeans b/bashbeans
--- a/bashbeans
+++ b/bashbeans
@@ -3,6 +3,8 @@
 #todo
 ##.bashbeans settings (global ~/. and per project and per machine)
 ###folders, classpath/ext, platform info, compilers, etc.,
+###cooperate with git (gitignore for machine specific and hashes)
+###detect machine settings (os, which md5sum?, )
 ##support for java and clojure
 ###put compiler scripts into global ~/.
 ###javac + compiler jars vs. scalac,clojurec,...
@@ -32,6 +34,7 @@ cd src
 echo "$projectname"
 
 #get arguments, process switches
+#@do it with getopt(s)
 if [ $# -gt 0 ]; then
     for i do
         case "$i" in #dont take the strings seriously - they're used as booleans ;)
@@ -46,15 +49,9 @@ if [ "$files" == "" ]; then
     files="  *.scala" 
 fi
 
-#@ temporary hack to do scala and clojure
-files1="  *.scala"
-files2="  *.clj"
-files="$files1$files2"
-
-
 #hash func
-##@getpath za $1?
-fileshash="`$hashfunc ../$0 ../compile.clj $files`" #must be compiled with same bashbeans script
+##@ getpath za $1?
+fileshash="`$hashfunc ../$0 $files`" #must be compiled with same bashbeans script
 #echo "$fileshash"
 
 #build
@@ -66,8 +63,9 @@ elif [ "$Force" == "" -a -e $hashpath -a "$fileshash" == "`cat $hashpath`" ]; th
     builderror="0"
 else
     builderror="0"
-    if [ "$builderror" == "0" ]; then
-        echo "Compiling:"$files2
+    #might still need it for Scala->Clojure interop :P
+    #if [ "$builderror" == "0" ]; then
+    #    echo "Compiling:"$files2
         #clojurec -d ../class -extdirs $files2
         
         #remove .clj
@@ -77,12 +75,14 @@ else
         #done
         #java -cp .:../class:../lib/clojure.jar -Dclojure.compile.path=../class clojure.lang.Compile $ffiles2
         #java -cp .:../class:../class/AngryPig:../lib/clojure.jar -Dclojure.compile.path=../class clojure.lang.Compile AngryPig.helloworld
-        builderror=$?
-    fi
+    #    builderror=$?
+    #fi
     if [ "$builderror" == "0" ]; then
-        echo "Compiling:"$files1
+        echo "Compiling:"$files
         #fast scala compile (loads compile deamon)
-        fsc -deprecation -cp ../class/AngryPig:../class:.:../lib/clojure.jar -d ../class -extdirs ../lib/lwjgl-2.7.1/jar/ $files1
+        #@detect if it says Deamon not loaded and retry, or fallback to scala
+        #@also this will be a part of compiler spec later
+        fsc -deprecation -cp ../class/AngryPigs:../class:.:../lib/clojure.jar -d ../class -extdirs ../lib/lwjgl-2.7.1/jar/ $files
         builderror=$?
     fi
     
@@ -98,7 +98,5 @@ echo "Done("$builderror") in ${elapsedtime}s."
 #run it
 if [ "$builderror" == "0" -a "$Run" != "" ]; then
     cd ..
-    #CP="lib/lwjgl-2.7.1/jar/lwjgl.jar:lib/lwjgl-2.7.1/jar/lwjgl_util.jar:class"
-    #cd $CD"class"
-    scala -cp src/:src/AngryPig:class/AngryPig:.:lib/lwjgl-2.7.1/jar/lwjgl.jar:lib/lwjgl-2.7.1/jar/lwjgl_util.jar:class:lib/clojure.jar -Djava.library.path="lib/lwjgl-2.7.1/native/macosx/:lib/lwjgl-2.7.1/native/linux/" AngryPig.$runname
+    scala -cp .:src/:src/AngryPigs:class/AngryPigs:lib/lwjgl-2.7.1/jar/lwjgl.jar:lib/lwjgl-2.7.1/jar/lwjgl_util.jar:class:lib/clojure.jar -Djava.library.path="lib/lwjgl-2.7.1/native/macosx/:lib/lwjgl-2.7.1/native/linux/" AngryPigs.Game
 fi
